### ISSUE TITLE
modules: remove strip_tags

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-3#277]
this as it's causing problems with outputting description..

**Comment by jojo12** [comment]
Because I didn't find this notice, I posted an answer in the forum. 
But now here:
I tried with the changes:
because these modules work with introtext and "readmore" your changes break the whole site
Even when you have titles and other html tags in the event description, it breaks too.
If you want to change that, then you have to change much more!
(this is for mod_jem_banner too!)

**Comment by JKoelman** [comment]
>  your changes break the whole site

not sure what you meant with breaking the whole site but by removing the strip_tags a lot more html code will be in the output and that can be usefull for people.  If it should be limited then people should have the option to fill in the tags they need.      At the moment only the <BR> tag was allowed and that's to limited.


> If you want to change that, then you have to change much more!

uhm, not really but will add an option where people can fill in the tags.

**Comment by JKoelman** [comment]
adapted the modules a bit so will close the issue
